[package]
name = "mediasoup"
version = "0.0.1"
description = "Cutting Edge WebRTC Video Conferencing"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]

[dependencies]
