[package]
name = "mediasoup"
version = "0.1.0"
description = "Cutting Edge WebRTC Video Conferencing in Rust"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]
documentation = "https://docs.rs/mediasoup"
repository = "https://github.com/nazar-pc/mediasoup/tree/rust"

[dependencies]
async-channel = "1.5.1"
async-executor = "1.4.0"
async-fs = "1.5.0"
async-io = "1.3.1"
async-mutex = "1.4.0"
async-oneshot = "0.4.2"
async-process = "1.0.1"
async-trait = "0.1.42"
bytes = "0.6.0"
event-listener-primitives = "0.2.2"
fastrand = "1.4.0"
futures-lite = "1.11.2"
h264-profile-level-id = "0.1.1"
log = "0.4.11"
libc = "0.2.81"
nix = "0.19.1"
once_cell = "1.5.2"
serde_json = "1.0.60"
thiserror = "1.0.22"

[dependencies.parking_lot]
version = "0.11.1"
features = ["serde"]

[dependencies.regex]
default-features = false
features = ["std", "perf"]
version = "1.4.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.118"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8.1"

[dev-dependencies]
env_logger = "0.8.2"
