[package]
name = "mediasoup"
version = "0.0.5"
description = "Cutting Edge WebRTC Video Conferencing"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]
documentation = "https://docs.rs/mediasoup"
repository = "https://github.com/nazar-pc/mediasoup/tree/rust"

[dependencies]
async-channel = "1.5.1"
async-executor = "1.3.0"
async-fs = "1.5.0"
async-io = "1.1.10"
async-mutex = "1.4.0"
async-oneshot = "0.4.1"
async-process = "1.0.1"
async-trait = "0.1.41"
bytes = "0.6.0"
event-listener-primitives = "0.1.0"
fastrand = "1.4.0"
futures-lite = "1.11.1"
log = "0.4.11"
libc = "0.2.79"
nix = "0.18.0"
once_cell = "1.4.1"
serde_json = "1.0.58"
thiserror = "1.0.21"

[dependencies.regex]
default-features = false
features = ["std", "perf"]
version = "1.3.9"

[dependencies.serde]
features = ["derive"]
version = "1.0.116"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8.1"

[dev-dependencies]
env_logger = "0.7.1"
