[package]
name = "mediasoup"
version = "0.0.1"
description = "Cutting Edge WebRTC Video Conferencing"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]

[dependencies]
async-executor = "0.2.1"
async-fs = "1.1.1"
async-channel = "1.4.1"
async-oneshot = "0.3.3"
async-process = "0.1.3"
futures-lite = "1.0.0"
log = "0.4.11"
nix = "0.18.0"

[dev-dependencies]
env_logger = "0.7.1"
