[package]
name = "mediasoup"
version = "0.0.1"
description = "Cutting Edge WebRTC Video Conferencing"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]

[dependencies]
async-process = "0.1.3"
libc = "0.2.76"
log = "0.4.11"

[dev-dependencies]
env_logger = "0.7.1"
