[package]
name = "mediasoup"
version = "0.0.1"
description = "Cutting Edge WebRTC Video Conferencing"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"
license = "ISC"
keywords = ["webrtc", "ortc", "sfu"]

[dependencies]
async-channel = "1.4.2"
async-executor = "1.0.0"
async-fs = "1.2.1"
async-io = "1.0.1"
async-mutex = "1.3.0"
async-oneshot = "0.3.3"
async-process = "1.0.0"
async-trait = "0.1.40"
futures-lite = "1.3.0"
log = "0.4.11"
libc = "0.2.76"
nix = "0.18.0"
serde_json = "1.0.57"
thiserror = "1.0.20"

[dependencies.rand]
features = ["small_rng"]
version = "0.7.3"

[dependencies.serde]
features = ["derive"]
version = "1.0.115"

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.8.1"

[dev-dependencies]
env_logger = "0.7.1"
