name: C++

on:
  push:
    branches: [ v3 ]

jobs:
  ci:
    strategy:
      matrix:
        os:
#          - ubuntu-16.04
#          - ubuntu-18.04
          - ubuntu-20.04
          - macos-10.15
          # macOS 11 is in private preview currently
          #- macos-11.0
          # Windows needs to be tuned before it can run, I didn't bother, feel free to contribute
          #- windows-2019
        # Just 1 Node.js version should be fine for C++
        node:
          - 14
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Configure cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            worker/deps
            worker/out
          key: ${{ matrix.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-

      - run: npm install
      - run: npm run lint:worker
      - run: npm run test:worker
