name: mediasoup-node

on: [push, pull_request]

concurrency:
  # Cancel a currently running workflow from the same PR, branch or tag when a
  # new workflow is triggered.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      matrix:
        # Different Node versions on Ubuntu, the latest Node on other platforms.
        ci:
          - os: ubuntu-22.04
            node: 16
            cc: gcc
            cxx: g++
          - os: ubuntu-22.04
            node: 18
            cc: gcc
            cxx: g++
          - os: macos-12
            node: 18
            cc: clang
            cxx: clang++
          - os: windows-2022
            node: 18
            cc: cl
            cxx: cl

    runs-on: ${{ matrix.ci.os }}

    env:
      CC: ${{ matrix.ci.cc }}
      CXX: ${{ matrix.ci.cxx }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.ci.node }}

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
          key: ${{ matrix.ci.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ matrix.ci.os }}-node-

      - run: npm ci
      - run: npm run lint:node
      - run: npm run test:node
