name: mediasoup-pack

on:
  push:
    tags:
    - v*  # Only build for tags that match new versions of `npm` packages
  # Manual dispatch, only for testing purposses
  # See https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  linux-x64:
    name: Create prebuild image for Linux x86_64

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2

      - run: npm run worker:build

      - uses: actions/upload-artifact@v2
        with:
          name: linux-x64
          path: worker/out/linux-x64/Release/mediasoup-worker
          retention-days: 1

  macos-x64:
    name: Create prebuild image for macOS x86_64

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2

      - run: npm run worker:build

      - uses: actions/upload-artifact@v2
        with:
          name: darwin-x64
          path: worker/out/darwin-x64/Release/mediasoup-worker
          retention-days: 1

  windows-x64:
    name: Create prebuild image for Windows x86_64

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js
        uses: actions/setup-node@v2

      - run: npm run worker:build

      - uses: actions/upload-artifact@v2
        with:
          name: win32-x64.exe
          path: worker/out/win32-x64/Release/mediasoup-worker.exe
          retention-days: 1

  pack:
    name: Bundle the prebuild images and publish the package

    needs: [linux-x64, macos-x64, windows-x64]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: linux-x64
          path: worker/out/linux-x64/Release/mediasoup-worker
      - uses: actions/download-artifact@v2
        with:
          name: darwin-x64
          path: worker/out/darwin-x64/Release/mediasoup-worker
      - uses: actions/download-artifact@v2
        with:
          name: win32-x64.exe
          path: worker/out/win32-x64/Release/mediasoup-worker.exe

      - run: chmod +x worker/out/*/Release/mediasoup-worker

      - name: Node.js
        uses: actions/setup-node@v2

      - run: npm publish  # This will build the package again too.
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
