name: mediasoup-rust

on: [push, pull_request]

concurrency:
  # Cancel a currently running workflow from the same PR, branch or tag when a
  # new workflow is triggered.
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-22.04
          - macos-12
          - windows-2022

    runs-on: ${{ matrix.os }}

    env:
      KEEP_BUILD_ARTIFACTS: '1'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}

      # TODO: Temporal until we decide how to deal with pip invoke requirement.
      - name: pip install invoke
        run: python3 -m pip install invoke

      - name: cargo fmt
        run: cargo fmt --all -- --check

      - name: cargo clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo test
        run: cargo test --verbose
